### ISSUE TITLE
Native image error: Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/  

### ISSUE THREAD

**Issue by dinosath** [quarkiverse/quarkus-cxf#238]
I build a native image using with GRAALVM via docker. The build is successful , but when i try to run my application i ​get the following error 

`Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/`

In my project dependencies are quarkus-cxf version 0.8 and Quarkus version 1.13.5.Final.
I use the cxf-codegen-plugin v3.4.3 to generate source code from a given wsdl and inject the CXFClient

**Comment by dinosath** [comment]
I also tried adding the bus-extension.txt and wsdl.plugin.xml via resources-config.json , when you want to add resources in native image , but still the same error.

**Comment by dufoli** [comment]
it come from 
https://github.com/apache/cxf/blob/75fb6bb56d82f72771a9ee6ecab5d36168303f51/rt/frontend/simple/src/main/java/org/apache/cxf/frontend/AbstractWSDLBasedEndpointFactory.java
but do you have the exception.
Or enable debug to get it ?
to have detail about why it throw exception.

**Comment by dufoli** [comment]
lead reflection on ExtensibilityElement to check.
Can you detail your project and config and of course the url you are checking with body.

**Comment by dinosath** [comment]
Hello , in my project i have a REST service that call a SOAP service and transform that response to another JSON model. In the cxf-codegen-plugin i have added some bindings. With extraarg -b. Even if i delete the extra arg the error is the same. 

`Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:361)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpointInfo(AbstractWSDLBasedEndpointFactory.java:268)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:146)
        at org.apache.cxf.frontend.ClientFactoryBean.create(ClientFactoryBean.java:91)
        at org.apache.cxf.frontend.ClientProxyFactoryBean.create(ClientProxyFactoryBean.java:159)
        at org.apache.cxf.jaxws.JaxWsProxyFactoryBean.create(JaxWsProxyFactoryBean.java:142)
        at io.quarkiverse.cxf.CxfClientProducer.produceCxfClient(CxfClientProducer.java:121)
        at io.quarkiverse.cxf.CxfClientProducer.loadCxfClient(CxfClientProducer.java:58)
        at com.example.ws.client.order.OrderInterfaceCxfClientProducer.createService(OrderInterfaceCxfClientProducer.zig:39)
        at com.example.ws.client.order.OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.create(OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.zig:210)
        at com.example.ws.client.order.OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.get(OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.zig:240)
        at com.example.ws.client.order.OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.get(OrderInterfaceCxfClientProducer_ProducerMethod_createService_ae24ce3702b11fedf88d08b28907a75d7b63d9ad_Bean.zig:275)
        at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:52)
        at com.example.soap.OrdersSoapClient_Bean.create(OrdersSoapClient_Bean.zig:245)
        ... 45 more
Caused by: org.apache.cxf.BusException: No binding factory for namespace http://schemas.xmlsoap.org/wsdl/soap/ registered.
        at org.apache.cxf.bus.managers.BindingFactoryManagerImpl.getBindingFactory(BindingFactoryManagerImpl.java:93)
        at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createBindingInfo(AbstractWSDLBasedEndpointFactory.java:348)
        ... 58 more`

**Comment by dufoli** [comment]
Hmmm. I have checked and found the issue.
all binding factory must be loaded with field and method in reflection and I handle only one in bus-extensions.txt

org.apache.cxf.wsdl.binding.AbstractWSDLBindingFactory
org.apache.cxf.binding.xml.XMLBindingFactory 
org.apache.cxf.binding.corba.CorbaBindingFactory
org.apache.cxf.bindings.soap.SOAPBindingFactory
org.apache.cxf.binding.soap.SoapBindingFactory => rt/bindings/soap/src/main/resources/META-INF/cxf/bus-extensions.txt so ok
org.apache.cxf.binding.AbstractBindingFactory

**Comment by dufoli** [comment]
maybe I can clean up more the list. When I register for reflection a class, maybe interface and abstract class must not been declared. I am thinking to Bus class for example. I am not sure it is usefull to add it.

**Comment by shumonsharif** [comment]
@dinosath are you by any chance able to update the attached to reproduce the issue you are seeing?
[quarkus-cxf-238.zip](https://github.com/quarkiverse/quarkus-cxf/files/6563731/quarkus-cxf-238.zip)

You can run `mvn clean verify -Dnative` to execute the native integration test.

**Comment by dufoli** [comment]
any news here ?
@shumonsharif else I can add all refelction build item class....

**Comment by shumonsharif** [comment]
Hey @dufoli sounds good to me ... I was hoping we could at least verify whether the changes fix the issues @dinosath is having ... but not sure if we can get a reproducer.  So let's add the build item classes, and keep our fingers crossed!

**Comment by dinosath** [comment]
Hello , i triead finding a public wsdl that generatesbthe same issue but was not able to do it. Sadly the wsdl i use in my case is proprietary , so i cannot share it.

**Comment by shumonsharif** [comment]
@dinosath for all we know, you may have an invalid WSDL, or one that CXF cannot handle ... it's difficult to help you without a reproducer; this also seems to be an edge case that hasn't been encountered by others yet.  Are you able to put together a simple WSDL that's representative of your proprietary one?

Hopefully the patch @dufoli puts in will address your issue, and you're able to test it for us, but we're essentially throwing darts in the dark here ... :)

**Comment by dinosath** [comment]
Yeah i know it is hard to address the issue without a project that reproduce the problem and is accessible. Truthfully i hoped others encountered the issue as well... 

The wsdl is ok because we already use plain cxf in our quarkus project.

**Comment by dufoli** [comment]
OK so we will add all class to reflection for native and if you can test the branch before merge it will be perfect.

**Comment by dufoli** [comment]
@dinosath  can you test with version of branch issue238 ?

**Comment by dufoli** [comment]
I have just added binding

**Comment by dinosath** [comment]
Yes i can test it. It is the least i can do , since i can not provide a wsdl file.

**Comment by dinosath** [comment]
I tested it and the issue remains.

**Comment by shumonsharif** [comment]
> The wsdl is ok because we already use plain cxf in our quarkus project.

@dinosath are you able to share a cleansed version of your pom.xml?

**Comment by dufoli** [comment]
Can you share interface or at least obfuscated signature of method

**Comment by dinosath** [comment]
Hello , sadly i cannot share the pom.xml. But i am sure it is not an issue with my pom because in the cxf-238.zip project i replaced the hello.wsdl with mine and no other changes apart from the cxfclient interface. The issue persists for both 0.8 and 0.9.0-SNAPSHOT from branch issue238.

**Comment by dinosath** [comment]
@dufoli this is an obfuscated signature of the method i used from the interface that is generated from the cxf-codegen plugin
`    @WebMethod(operationName = "GetCustomList", action = "http://sample.data.com/contract/v1/get-list")
    @Action(input = "http://sample.data.com/contract/v1/get-list", fault = {})
    @WebResult(name = "GetCustomListResponseModel", targetNamespace = "http://sample.data.com/schema/custom/v1", partName = "CustomList")
    public GetCustomListResponseModel getCustomList(
        @WebParam(partName = "CustomCriteria", name = "GetCustomListRequestModel", targetNamespace = "http://sample.data.com/schema/custom/v1")
        GetCustomListRequestModel customCriteria,
        @WebParam(partName = "H1", name = "Header1", targetNamespace = "http://sample.data.com/contract/header/v1", header = true)
        Header1 h1,
        @WebParam(partName = "H2", name = "Header2", targetNamespace = "http://sample.data.com/contract/header/v1", header = true)
        Header2 h2
    ) throws CustomFault;
`

**Comment by dinosath** [comment]
@dufoli Also the interface that i inject as cxfclient obfuscated
`@WebService(targetNamespace = "http://sample.data.com/contract/v1", name = "CustomInterface")
@XmlSeeAlso({com.sample.data.schema.ObjectFactory.class, com.sample.data.contract.fault.v1.ObjectFactory.class, com.sample.dataschema.common.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomInterface {}
`

**Comment by shumonsharif** [comment]
> @shumonsharif Hello , sadly i cannot share the pom.xml. But i am sure it is not an issue with my pom because in the cxf-238.zip project i replaced the hello.wsdl with mine and no other changes apart from the cxfclient interface. The issue persists for both 0.8 and 0.9.0-SNAPSHOT from branch issue238.

Thanks for clarifying @dinosath ... there's clearly something unique to your WSDL and/or supporting schemas that's not getting handled properly.  The info we've gathered so far is quite limited, and not helpful enough to address this issue.

My only suggestion is that you try modifying the hello.wsdl to see how it impacts things.  Start simple with the working version of `quarkus-cxf-238.zip`, and copy over one operation at a time (from your WSDL) to it, until things break.  Let us know how it goes.

**Comment by shumonsharif** [comment]
Also the below will provide additional logging details ... add to your `application.properties` ... let us know if you discover anything new!

```java
quarkus.log.level=INFO
quarkus.log.category."org.apache.cxf".level=TRACE
quarkus.log.category."io.quarkiverse.cxf".level=TRACE
```

**Comment by comrt** [comment]
> @dinosath are you by any chance able to update the attached to reproduce the issue you are seeing?
> [quarkus-cxf-238.zip](https://github.com/quarkiverse/quarkus-cxf/files/6563731/quarkus-cxf-238.zip)
> 
> You can run `mvn clean verify -Dnative` to execute the native integration test.

Hello, i stumbled over the same problem, i ran your example on my Windows 10 machine with the given command. 
Result is:
Caused by: org.apache.cxf.BusException: No binding factory for namespace http://schemas.xmlsoap.org/wsdl/soap/ registered.

Next thing i did, is building the app with the property quarkus.native.container-build=true as a docker image and ran it. Same result.

In the build log i can see several nullpointerexceptions, which i can't get my head around.
I attached the buildlog from the native build on windows - hope it helps somehow.

[buildlog.txt](https://github.com/quarkiverse/quarkus-cxf/files/6657711/buildlog.txt)

**Comment by shumonsharif** [comment]
Hi @comrt can you please try to add -Dquarkus.native.auto-service-loader-registration=true to your build and let us know the results?  The NPEs can safely be ignored - they are logged as DEBUG statements by the extension.

**Comment by comrt** [comment]
@shumonsharif i switched to jvm11 and ran it with the parameter. It doesn't work, the native image cannot be built, it fails with:

`Error: Unsupported features in 4 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.jvnet.mimepull.MIMEPart. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace:
        at parsing com.sun.xml.messaging.saaj.soap.AttachmentPartImpl$1.getContentType(AttachmentPartImpl.java:175)
Call path from entry point to com.sun.xml.messaging.saaj.soap.AttachmentPartImpl$1.getContentType():
        at com.sun.xml.messaging.saaj.soap.AttachmentPartImpl$1.getContentType(AttachmentPartImpl.java:175)
        at javax.activation.DataSourceDataContentHandler.writeTo(DataHandler.java:791)
        at javax.activation.DataHandler$1.run(DataHandler.java:249)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
        at com.oracle.svm.core.code.IsolateEnterStub.WindowsJavaThreads_osThreadStartRoutine_4bc03aa26f8cdfc97ebd54050e8ae4bce1023851(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.jvnet.mimepull.MIMEPart. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.`

Please see the full build log as attachement
[buildlog-2021-06-16.txt](https://github.com/quarkiverse/quarkus-cxf/files/6660265/buildlog-2021-06-16.txt)

Then i added the parameter --allow-incomplete-classpath to the nativa build args, it runs the test but fails with:
`ERROR: Failed to start application (with profile prod)
java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.FilterConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at java.lang.Class.newInstance(DynamicHub.java:883)
        at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:23)
        at org.jboss.resteasy.microprofile.config.FilterConfigSource.<init>(FilterConfigSource.java:21)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:90)
        at io.smallrye.config.SmallRyeConfig.buildConfigSources(SmallRyeConfig.java:83)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:66)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:360)
        at io.quarkus.runtime.generated.Config.readConfig(Config.zig:1165)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:42)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:345)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
`

**Comment by shumonsharif** [comment]
@comrt Thank you - I believe we may have made some progress here, and identified a potential issue.  @dufoli Do you have some thoughts on `org.jvnet.mimepull.MIMEPart` for reflection?

Regarding the following error, it seems to have popped up now and then (you can search the Quarkus issues), and is unrelated to this extension.
`ERROR: Failed to start application (with profile prod) java.lang.InstantiationException: Type org.jboss.resteasy.microprofile.config.FilterConfigSourceImpl can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.`

As a workaround, you may need to add a reflection-config.json file (there's an example you can refer to [here](https://github.com/quarkiverse/quarkus-cxf/issues/199#issuecomment-834951523)):
https://github.com/quarkiverse/quarkus-cxf/files/6444938/changes.zip

**Comment by dufoli** [comment]
maybe add reflection for 
MIMEMultipartRelated
and org.jvnet.mimepull.MIMEPart
but not sure

**Comment by shumonsharif** [comment]
@dufoli I agree - org.jvnet.mimepull.MIMEPart should not be getting used by CXF, the library doesn't even appear in the dependency tree for me.

@comrt are you running the `quarkus-cxf-238.zip` as is, or did you add anything to it?  Can you run `mvn dependency:tree` for us?  Also, if you would please share your JDK details with `java -version`?

**Comment by comrt** [comment]
@shumonsharif i only added the additional args (--allow-incomplete-classpath), when suggested by the build output. 

Here's the JDK i used:
`java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
`
Dependencies
`mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme:quarkus-cxf-238 >----------------------
[INFO] Building quarkus-cxf-238 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ quarkus-cxf-238 ---
[INFO] org.acme:quarkus-cxf-238:jar:1.0.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy-jaxb:jar:1.13.5.Final:compile
[INFO] |  +- io.quarkus:quarkus-jaxb:jar:1.13.5.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile
[INFO] |  |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile
[INFO] |  +- org.jboss.resteasy:resteasy-jaxb-provider:jar:4.5.12.Final:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  \- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile
[INFO] +- io.quarkus:quarkus-resteasy-jsonb:jar:1.13.5.Final:compile
[INFO] |  +- io.quarkus:quarkus-jsonb:jar:1.13.5.Final:compile
[INFO] |  |  +- org.eclipse:yasson:jar:1.0.9:compile
[INFO] |  |  \- io.quarkus:quarkus-jsonp:jar:1.13.5.Final:compile
[INFO] |  +- org.jboss.resteasy:resteasy-json-binding-provider:jar:4.5.12.Final:compile
[INFO] |  |  +- org.glassfish:jakarta.json:jar:1.1.6:compile
[INFO] |  |  \- jakarta.json.bind:jakarta.json.bind-api:jar:1.0.2:compile
[INFO] |  +- org.jboss.resteasy:resteasy-json-p-provider:jar:4.5.12.Final:compile
[INFO] |  \- commons-io:commons-io:jar:2.8.0:compile
[INFO] +- io.quarkus:quarkus-smallrye-openapi:jar:1.13.5.Final:compile
[INFO] |  +- io.smallrye:smallrye-open-api-core:jar:2.0.26:compile
[INFO] |  |  +- org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:1.1.3-RC1:compile
[INFO] |  |  +- org.eclipse.microprofile.config:microprofile-config-api:jar:1.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.3:compile
[INFO] |  |  |  \- org.yaml:snakeyaml:jar:1.28:compile
[INFO] |  |  \- org.jboss:jandex:jar:2.2.3.Final:compile
[INFO] |  +- io.quarkus:quarkus-core:jar:1.13.5.Final:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile
[INFO] |  |  |  +- jakarta.el:jakarta.el-api:jar:3.0.3:compile
[INFO] |  |  |  \- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile
[INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile
[INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:1.13.5.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:1.13.5.Final:compile
[INFO] |  |  +- io.smallrye.config:smallrye-config:jar:1.13.1:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-annotation:jar:1.5.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-expression:jar:1.5.0:compile
[INFO] |  |  |  |  \- io.smallrye.common:smallrye-common-function:jar:1.5.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-constraint:jar:1.5.0:compile
[INFO] |  |  |  +- io.smallrye.common:smallrye-common-classloader:jar:1.5.0:compile
[INFO] |  |  |  \- io.smallrye.config:smallrye-config-common:jar:1.13.1:compile
[INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.9:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.0.Final:compile
[INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.2.0.Final:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile
[INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:21.0.0:compile
[INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
[INFO] |  |  \- io.quarkus:quarkus-bootstrap-runner:jar:1.13.5.Final:compile
[INFO] |  +- io.quarkus:quarkus-vertx-http:jar:1.13.5.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-security-runtime-spi:jar:1.13.5.Final:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-http-dev-console-runtime-spi:jar:1.13.5.Final:compile
[INFO] |  |  +- io.quarkus.security:quarkus-security:jar:1.1.4.Final:compile
[INFO] |  |  |  \- io.smallrye.reactive:mutiny:jar:0.14.0:compile
[INFO] |  |  |     \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] |  |  +- io.quarkus:quarkus-vertx-core:jar:1.13.5.Final:compile
[INFO] |  |  |  +- io.quarkus:quarkus-netty:jar:1.13.5.Final:compile
[INFO] |  |  |  |  +- io.netty:netty-codec:jar:4.1.49.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-handler:jar:4.1.49.Final:compile
[INFO] |  |  |  \- io.vertx:vertx-core:jar:3.9.6:compile
[INFO] |  |  |     +- io.netty:netty-common:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-buffer:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-transport:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-handler-proxy:jar:4.1.49.Final:compile
[INFO] |  |  |     |  \- io.netty:netty-codec-socks:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-codec-http:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-codec-http2:jar:4.1.49.Final:compile
[INFO] |  |  |     +- io.netty:netty-resolver:jar:4.1.49.Final:compile
[INFO] |  |  |     \- io.netty:netty-resolver-dns:jar:4.1.49.Final:compile
[INFO] |  |  |        \- io.netty:netty-codec-dns:jar:4.1.49.Final:compile
[INFO] |  |  \- io.vertx:vertx-web:jar:3.9.6:compile
[INFO] |  |     +- io.vertx:vertx-web-common:jar:3.9.6:compile
[INFO] |  |     +- io.vertx:vertx-auth-common:jar:3.9.6:compile
[INFO] |  |     \- io.vertx:vertx-bridge-common:jar:3.9.6:compile
[INFO] |  \- io.quarkus:quarkus-swagger-ui:jar:1.13.5.Final:compile
[INFO] +- io.quarkus:quarkus-arc:jar:1.13.5.Final:compile
[INFO] |  +- io.quarkus.arc:arc:jar:1.13.5.Final:compile
[INFO] |  |  \- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  \- org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api:jar:1.0.1:compile
[INFO] +- io.quarkus:quarkus-resteasy:jar:1.13.5.Final:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-server-common:jar:1.13.5.Final:compile
[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:1.13.5.Final:compile
[INFO] |     |  \- org.jboss.resteasy:resteasy-core:jar:4.5.12.Final:compile
[INFO] |     |     +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile
[INFO] |     |     +- org.jboss.resteasy:resteasy-core-spi:jar:4.5.12.Final:compile
[INFO] |     |     \- com.ibm.async:asyncutil:jar:0.1.0:compile
[INFO] |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] +- io.quarkiverse.cxf:quarkus-cxf:jar:0.8:compile
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxws:jar:3.4.3:compile
[INFO] |  |  +- xml-resolver:xml-resolver:jar:1.2:compile
[INFO] |  |  +- org.apache.cxf:cxf-core:jar:3.4.3:compile
[INFO] |  |  |  +- com.fasterxml.woodstox:woodstox-core:jar:6.1.1:compile
[INFO] |  |  |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2:compile
[INFO] |  |  |  \- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-soap:jar:3.4.3:compile
[INFO] |  |  |  +- org.apache.cxf:cxf-rt-wsdl:jar:3.4.3:compile
[INFO] |  |  |  |  \- wsdl4j:wsdl4j:jar:1.6.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-databinding-jaxb:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-bindings-xml:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-frontend-simple:jar:3.4.3:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-ws-addr:jar:3.4.3:compile
[INFO] |  |  |  \- org.apache.cxf:cxf-rt-ws-policy:jar:3.4.3:compile
[INFO] |  |  |     \- org.apache.neethi:neethi:jar:3.1.1:compile
[INFO] |  |  +- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.3:compile
[INFO] |  |  +- jakarta.jws:jakarta.jws-api:jar:2.1.0:compile
[INFO] |  |  +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.2:compile
[INFO] |  |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  |  +- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] |  |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.2:runtime
[INFO] |  |  |  \- org.jvnet.staxex:stax-ex:jar:1.8.3:runtime
[INFO] |  |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO] |  +- jakarta.servlet:jakarta.servlet-api:jar:4.0.3:compile
[INFO] |  +- org.apache.cxf:cxf-rt-transports-http:jar:3.4.3:compile
[INFO] |  |  \- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  +- io.quarkus:quarkus-jaxp:jar:1.13.5.Final:compile
[INFO] |  \- io.quarkus:quarkus-jackson:jar:1.13.5.Final:compile
[INFO] |     +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3:compile
[INFO] |     +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.12.3:compile
[INFO] |     \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.12.3:compile
[INFO] +- io.quarkus:quarkus-junit5:jar:1.13.5.Final:test
[INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:1.13.5.Final:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:1.13.5.Final:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:1.13.5.Final:test
[INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.1:test
[INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.8.1:test
[INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:test
[INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.2:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.2:test
[INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.2.1:test
[INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.1:test
[INFO] |  |  |  |  |  \- com.google.guava:guava:jar:30.1-jre:test
[INFO] |  |  |  |  |     +- com.google.guava:failureaccess:jar:1.0.1:test
[INFO] |  |  |  |  |     \- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-utils:jar:3.2.1:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test
[INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test
[INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.4:test
[INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.1:test
[INFO] |  |  |  |  +- org.codehaus.plexus:plexus-interpolation:jar:1.25:test
[INFO] |  |  |  |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.4:test
[INFO] |  |  |  |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:test
[INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.1:test
[INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.2:test
[INFO] |  |  |  |  \- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.2:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.2:test
[INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.2:test
[INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.4.3:test
[INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.4.3:test
[INFO] |  |  |  |  |  \- org.jsoup:jsoup:jar:1.12.1:test
[INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.4.3:test
[INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.4.3:test
[INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:1.13.5.Final:test
[INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.5.0:compile
[INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.4:test
[INFO] |  +- io.quarkus:quarkus-test-common:jar:1.13.5.Final:test
[INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:1.13.5.Final:test
[INFO] |  |  |  +- io.quarkus.gizmo:gizmo:jar:1.0.7.Final:test
[INFO] |  |  |  |  \- org.ow2.asm:asm-util:jar:9.1:test
[INFO] |  |  |  |     +- org.ow2.asm:asm-tree:jar:9.1:test
[INFO] |  |  |  |     \- org.ow2.asm:asm-analysis:jar:9.1:test
[INFO] |  |  |  +- org.ow2.asm:asm:jar:9.1:test
[INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:1.13.5.Final:test
[INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:1.13.5.Final:test
[INFO] |  |  |  \- io.quarkus:quarkus-builder:jar:1.13.5.Final:test
[INFO] |  |  +- io.quarkus:quarkus-jsonp-deployment:jar:1.13.5.Final:test
[INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.7.1:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.7.1:test
[INFO] |  |  |  +- org.apiguardian:apiguardian-api:jar:1.1.0:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  \- org.junit.platform:junit-platform-commons:jar:1.7.1:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.7.1:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.7.1:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.7.1:test
[INFO] |  +- io.quarkus:quarkus-datasource-deployment-spi:jar:1.13.5.Final:test
[INFO] |  |  +- io.quarkus:quarkus-arc-deployment:jar:1.13.5.Final:test
[INFO] |  |  |  +- io.quarkus:quarkus-vertx-http-dev-console-spi:jar:1.13.5.Final:test
[INFO] |  |  |  \- io.quarkus.arc:arc-processor:jar:1.13.5.Final:test
[INFO] |  |  \- io.quarkus:quarkus-datasource-common:jar:1.13.5.Final:test
[INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.16:test
[INFO] |     \- io.github.x-stream:mxparser:jar:1.2.1:test
[INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:test
[INFO] \- io.rest-assured:rest-assured:jar:4.3.3:test
[INFO]    +- org.codehaus.groovy:groovy:jar:3.0.5:test
[INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.7:test
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:test
[INFO]    |  +- org.apache.httpcomponents:httpcore:jar:4.4.14:test
[INFO]    |  \- commons-codec:commons-codec:jar:1.14:test
[INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test
[INFO]    +- org.hamcrest:hamcrest:jar:2.1:test
[INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test
[INFO]    +- io.rest-assured:json-path:jar:4.3.3:test
[INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.5:test
[INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.3.3:test
[INFO]    \- io.rest-assured:xml-path:jar:4.3.3:test
[INFO]       +- org.apache.commons:commons-lang3:jar:3.12.0:test
[INFO]       +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO]       \- com.sun.xml.bind:jaxb-impl:jar:2.3.3:test
`

**Comment by shumonsharif** [comment]
@dufoli You're right, I think the `quarkus.native.auto-service-loader-registration=true` flag is what resulted in the JDK loading its internal implementation, which in turn needs `org.jvnet.mimepull.MIMEPart`.  So using that flag is not a good option for us.

@comrt Can you please try the attached [quarkus-cxf-238.zip](https://github.com/quarkiverse/quarkus-cxf/files/6665085/quarkus-cxf-238.zip) with `mvn clean verify -Dnative`?  The main changes in this version include:

Added a reflection-config.json file containing:
- org.apache.cxf.wsdl.JAXBExtensionHelper
- org.apache.cxf.databinding.source.mime.MimeAttribute
- javax.wsdl.extensions.mime.MIMEMultipartRelated

Updated the resources-config.json to include:
      "pattern": "META-INF/services/.*"

It may still break, but hopefully we can gather some additional info.

**Comment by comrt** [comment]
@shumonsharif 
it breaks again at integration test phase with `"Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/" `.
[buildlog-2021-06-016.txt](https://github.com/quarkiverse/quarkus-cxf/files/6665244/buildlog-2021-06-016.txt)

Did try  `mvn clean package -Pnative -Dquarkus.native.container-build=true` as well and tested it manually via docker. 
Still the same issue.

**Comment by shumonsharif** [comment]
@comrt Thanks for your support with this issue - we are unable to reproduce the issue, so we'll need your help to continue troubleshooting!  I'm running out of ideas here, though I'm thinking it could be JDK / GraalVM related.  

Can you please try one more thing for us ...

Update your pom.xml with the line below, and then build with `-Dquarkus.native.auto-service-loader-registration=true`
```
<quarkus.native.additional-build-args>--report-unsupported-elements-at-runtime,--enable-url-protocols=jar,-H:ResourceConfigurationFiles=resources-config.json,-H:ReflectionConfigurationFiles=reflection-config.json,-H:ServiceLoaderFeatureExcludeServices=javax.xml.soap.MessageFactory,-H:ServiceLoaderFeatureExcludeServices=javax.xml.soap.SOAPFactory,-H:ServiceLoaderFeatureExcludeServices=javax.xml.soap.SAAJMetaFactory</quarkus.native.additional-build-args>
```

**Comment by comrt** [comment]
@shumonsharif welcome, no thanks needed, you're doing a great job with this project here.

tried it, still no luck...
[buildlog-2021-06-17.txt](https://github.com/quarkiverse/quarkus-cxf/files/6667245/buildlog-2021-06-17.txt)

i'm still curious, why it's not working with `-Dquarkus.native.container-build=true` and the supported docker files, does it work for you?

**Comment by shumonsharif** [comment]
@comrt I may be missing something here; how are you executing and running the unit tests for the docker generated binary?  I am on Mac OS, the docker build generates a Linux binary that can't execute ... with error `cannot execute binary file`.  Can you share some details on what you're running and the output?

**Comment by shumonsharif** [comment]
FWIW @comrt , I built the docker image manually, ran it, and initiated a request using the following curl:

`curl -H "Content-Type: application/json" --data 'Shumon' http://localhost:8080/rest/hello`

Everything worked fine as expected.  I've attached all the commands and respective logs.  Kindly let us know if you notice any differences from your results.
[01-mvn-native.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670210/01-mvn-native.txt)
[02-docker-build.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670213/02-docker-build.txt)
[03-docker-run-curl.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670216/03-docker-run-curl.txt)

**Comment by comrt** [comment]
@shumonsharif  i used `mvn clean package -Pnative -Dquarkus.native.container-build=true`, which doesn't execute the IT-Tests but still creates the binary.
Then i used the same commands as you to push the binary to the docker and ran the created image.

I reproduced your steps:
[01-mvn-native.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670780/01-mvn-native.txt)
[02-docker-build.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670781/02-docker-build.txt)
[03-docker-run-curl.txt](https://github.com/quarkiverse/quarkus-cxf/files/6670782/03-docker-run-curl.txt)

What i can see is the following: `[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Uber JAR strategy is used for native image source JAR generation on Windows. This is done for the time being to work around a current GraalVM limitation on Windows concerning the maximum command length (see https://github.com/oracle/graal/issues/238
7).` does it influence the binary result?

**Comment by comrt** [comment]
@shumonsharif  I will try to get my hands on a Mac OS or Linux system and test it there. Maybe it's just a Windows GraalVM Problem.

**Comment by shumonsharif** [comment]
@comrt The docker native build is not using Windows GraalVM - but would be great if you could try out a Mac OS or Linux system, curious what result you get.  Just a random thought occurred to me - could it be related to locale settings?

**Comment by comrt** [comment]
@shumonsharif It works on my MacBook...
`mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=12g`
[mac-mvn-native.txt](https://github.com/quarkiverse/quarkus-cxf/files/6671625/mac-mvn-native.txt)
[mac-docker-run-curl.txt](https://github.com/quarkiverse/quarkus-cxf/files/6671626/mac-docker-run-curl.txt)
Seems to have something to do with the environment.

**Comment by shumonsharif** [comment]
@comrt Thanks for confirming!!  Definitely appears as though it may be environment related.  A little bizarre though that the docker image build would behave differently ... that's unexpected!

**Comment by comrt** [comment]
Next thing i tried, is building the binary on WSL and ran it there, works.
What i did next, is pushing the binary - built on WSL - into a docker image on Windows itself, works also.

Somehow the image gets build differently on Windows than any other OS.
My suggestion is indeed the native image source JAR. Doesn't the binary get built on top of that?
Take a look at the warnings:
`[INFO] [io.quarkiverse.cxf.deployment.QuarkusCxfProcessor] producing dedicated CXFClientInfo bean named 'com.learnwebservices.services.hello.HelloEndpoint' for SEI com.learnwebservices.services.hello.HelloEndpoint
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Uber JAR strategy is used for native image source JAR generation on Windows. This is done for the time being to work around a current GraalVM limitation on Windows concerning the maximum command length (see https://github.com/oracle/graal/issues/238
7).
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: D:\data\junk\quarkus-cxf-238-2\target\quarkus-cxf-238-1.0.0-SNAPSHOT-native-image-source-jar\quarkus-cxf-238-1.0.0-SNAPSHOT-runner.jar
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [jakarta.transaction:jakarta.transaction-api::jar:1.3.3(compile), org.apache.geronimo.specs:geronimo-jta_1.1_spec::jar:1.1.1(compile)] contain duplicate files, e.g. javax/transaction/UserT
ransaction.class
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [com.sun.activation:jakarta.activation::jar:1.2.1(compile), jakarta.activation:jakarta.activation-api::jar:1.2.1(compile)] contain duplicate files, e.g. javax/activation/ActivationDataFlav
or.class
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.cxf:cxf-rt-frontend-simple::jar:3.4.3(compile), org.apache.cxf:cxf-rt-ws-policy::jar:3.4.3(compile), org.apache.cxf:cxf-core::jar:3.4.3(compile), org.apache.cxf:cxf-rt-ws-addr:
:jar:3.4.3(compile), org.apache.cxf:cxf-rt-transports-http::jar:3.4.3(compile), org.apache.cxf:cxf-rt-bindings-soap::jar:3.4.3(compile), org.apache.cxf:cxf-rt-frontend-jaxws::jar:3.4.3(compile)] contain duplicate files, e.g. META-INF/spring.schemas
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.cxf:cxf-rt-frontend-simple::jar:3.4.3(compile), org.apache.cxf:cxf-core::jar:3.4.3(compile), org.apache.cxf:cxf-rt-transports-http::jar:3.4.3(compile), org.apache.cxf:cxf-rt-fr
ontend-jaxws::jar:3.4.3(compile)] contain duplicate files, e.g. META-INF/blueprint.handlers
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.cxf:cxf-rt-bindings-xml::jar:3.4.3(compile), org.apache.cxf:cxf-rt-bindings-soap::jar:3.4.3(compile)] contain duplicate files, e.g. META-INF/wsdl.plugin.xml
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.cxf:cxf-rt-frontend-simple::jar:3.4.3(compile), org.apache.cxf:cxf-rt-ws-policy::jar:3.4.3(compile), org.apache.cxf:cxf-core::jar:3.4.3(compile), org.apache.cxf:cxf-rt-ws-addr:
:jar:3.4.3(compile), org.apache.cxf:cxf-rt-databinding-jaxb::jar:3.4.3(compile), org.apache.cxf:cxf-rt-bindings-xml::jar:3.4.3(compile), org.apache.cxf:cxf-rt-transports-http::jar:3.4.3(compile), org.apache.cxf:cxf-rt-bindings-soap::jar:3.4.3(compile), org.apache.cxf:cxf-rt-frontend-jaxws::jar:3.4.3(compile), o
rg.apache.cxf:cxf-rt-wsdl::jar:3.4.3(compile)] contain duplicate files, e.g. META-INF/cxf/bus-extensions.txt
[WARNING] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Dependencies with duplicate files detected. The dependencies [org.apache.cxf:cxf-rt-frontend-simple::jar:3.4.3(compile), org.apache.cxf:cxf-rt-databinding-jaxb::jar:3.4.3(compile)] contain duplicate files, e.g. org/apache/cxf/endpoint/dynamic/simple
-binding.xjb
`

**Comment by shumonsharif** [comment]
Awesome, thanks @comrt for the additional testing, and I think you're right, the native sources are likely being used to create the native binary.  I tried looking into the referenced GraalVM #2387 and Quarkus #8860 issues, but couldn't figure out whether the fixes were ever addressed properly.  Will try to dig in some more later today ...

**Comment by dufoli** [comment]
I think we can open a bug on graalvm

**Comment by shumonsharif** [comment]
@dufoli @comrt As I understood it, the issue for GraalVM #2387 was already fixed.  I believe the core issue is that the Quarkus changes to address the original GraalVM Windows limitation needs to be reverted, as per:

https://github.com/quarkusio/quarkus/pull/8860/files#diff-e2e9394cec5c2edcecfcc2ee65fd6bedb2727a87b2864fa4d736bc4725d96569R635

**Comment by marcelbraghini** [comment]
hello
i'm facing a similar problem,  only occurs when I run the service from the jar (uber jar), when I go up with quarkus:dev it works perfectly

`Caused by: org.apache.cxf.service.factory.ServiceConstructionException: Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/`

you can test it on a sample project:
https://github.com/marcelbraghini/integrations

to see the error: `java -jar target/integrations-0.1.0-SNAPSHOT-runner.jar`

`curl --location --request GET 'localhost:8080/v1/endereco/89805350'`

**Comment by dufoli** [comment]
same issue than #194 . It was supposed to be fixed but I guess we have to check if ressources is well merged in quarkus for windows or if we have special stuff for that ? because native on windows seems to use uberjar.

**Comment by dufoli** [comment]
hmmm maybe solution is to change https://github.com/quarkiverse/quarkus-cxf/pull/218/files
by adding in test if windows && native same behaviour than uberjar to merge files in order to have 
because as @shumonsharif  provide link, the native on windows seems to use uberjar...
but if we do so we need to check if patch done on quarkus to use merged ressource work in native mode.

https://github.com/quarkusio/quarkus/pull/8860/files#diff-e2e9394cec5c2edcecfcc2ee65fd6bedb2727a87b2864fa4d736bc4725d96569R635

**Comment by shumonsharif** [comment]
@dufoli It appears uberjar is broken in general, even on Mac OS.  I doubled checked the `META-INF/cxf/bus-extensions.txt` and the `META-INF/wsdl.plugin.xml` files generated in @marcelbraghini 's projects uberjar - both files are getting merged properly and placed in the correct locations, but failing at runtime with `Could not resolve a binding for http://schemas.xmlsoap.org/wsdl/soap/`.  I would suggest we either reopen #194 or create a new issue to address uberjar.

**Comment by dufoli** [comment]
ohhhh noooo. Can you reopen on quarkus side and we will have to find a solution for that with quarkus team...

**Comment by comrt** [comment]
@shumonsharif @dufoli Thank you very much again for your investigations
From my perspective this is a 'issue' best addressed to the quarkus-project.
For the mean time i can work with a multistaged docker build as a workaround locally.
I'm just happy to know, it will work in our production environment. :-)
Big Thanks!

**Comment by shumonsharif** [comment]
@comrt Glad you have a workaround that gets you to production for now!

@dufoli It's been quite the hectic week at work - I will try to open an issue this weekend.  If you have some bandwidth before that, definitely feel free to open it as well!

**Comment by dufoli** [comment]
@shumonsharif  I open the issue.

**Comment by dufoli** [comment]
https://github.com/quarkusio/quarkus/issues/18168

**Comment by shumonsharif** [comment]
@dufoli I think the PR I just submitted should address these issues.  @comrt Can you please help us test on Windows native once @dufoli merges the PR?

**Comment by dufoli** [comment]
We just missed the https://github.com/quarkusio/quarkus/issues/5677 PR
Thanks @shumonsharif I have merged it.

**Comment by dufoli** [comment]
let s close and reopen if do not worked.

**Comment by comrt** [comment]
@shumonsharif sorry if i'm commenting on the closed issue, but i will test it with quarkus 2.0 and the master branch.

**Comment by shumonsharif** [comment]
@comrt no problem at all - and thanks once again for your help!  We'll reopen the issue in case it's still not fixed.

**Comment by comrt** [comment]
@shumonsharif  and @dufoli 
just tested it, works like a charm <3

- Win32-App built on graalvm-ce-java16-21.1.0 and

- Native image in docker container built on AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe

Great Work (y)

**Comment by dufoli** [comment]
@shumonsharif have you test on your side because I can close the quarkus bug
..

**Comment by shumonsharif** [comment]
@dufoli yes, let's close the Quarkus bug, glad this issue is finally resolved!

**Comment by marcelbraghini** [comment]
hello guys
i tested it here and it worked perfectly... the only thing that appears is a warning:

`
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/Users/marcelb/Projetos/integrations/target/integrations-0.1.0-SNAPSHOT-runner.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`

but thanks so much for the help

**Comment by shumonsharif** [comment]
@marcelbraghini Thanks, only suggestion I have is that you try the `-Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true` flag as a workaround.  You can read more about it here: 
https://stackoverflow.com/a/50251510

Also, including the following links in case we need to refer to these later ...
`https://github.com/eclipse-ee4j/jaxb-ri/issues/1197`
`https://github.com/eclipse-ee4j/jaxb-ri/issues/1501`

**Comment by marcelbraghini** [comment]
Oh, I get it, 
thanks man

**Comment by dufoli** [comment]
@shumonsharif maybe we can use NativeImageSystemPropertyBuildItem to set property or NativeImageConfigBuildItem but I guess first one is the best. wdyt ?

**Comment by shumonsharif** [comment]
@dufoli the warning only gets printed for uberjar mode, and not in native mode.  So I don't believe `NativeImageSystemPropertyBuildItem` will address it ... I think better to use just plain `SystemPropertyBuildItem`.
